### ISSUE TITLE
bug: Inheritance breaks when intermediate class doesn't declare member

### ISSUE THREAD

**Issue by thomasmarwitz** [mkdocstrings/griffe-inherited-docstrings#4]
### Description of the bug
During the inheriting of docstrings for a member, a direct parent class that doesn't have the member (e.g. `meth`) prevents a correct docstring inheritance from `A.meth -> B.meth`.

### To Reproduce

Run inside this module's environment:

```
from griffe import Extensions, temporary_visited_package

from griffe_inherited_docstrings.extension import InheritDocstringsExtension

code = """
# Base docstrings.
class A:
    def meth(self):
        '''A.'''

class AB(A):
    # This shouldn't break the inherting of docstrings.
    pass

class B(AB):
    def meth(self):
        ...

"""
with temporary_visited_package(
        "package",
        modules={"__init__.py": code},
        extensions=Extensions(InheritDocstringsExtension(merge=True)),
    ) as package:
        assert package["B.meth"].docstring # already fails here
        assert package["B.meth"].docstring.value == package["A.meth"].docstring.value
```

</details>

### Expected behavior

I expect the inheritance to work.

### Environment information
- __Python__: cpython 3.9.18 (/Users/XXXX/griffe-inherited-docstrings/.venv/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `griffe-inherited-docstrings` v1.1.0+d20241029

**Comment by thomasmarwitz** [comment]
I can work on a solution, if you want :)

**Comment by pawamoy** [comment]
Sure, that'd be great!
