### ISSUE TITLE
bug: Args not inherited in class docstrings

### ISSUE THREAD

**Issue by cnellington** [mkdocstrings/griffe-inherited-docstrings#6]
### Description of the bug
Google style supports `__init__` args in class docstrings `Args:` (e.g. class ExampleError in [Napoleon](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html)), but currently only attributes are inherited. Same with numpy style `Parameters`.  Args in class docstring also seem to work fine within vanilla mkdocstrings, but only break with inheritance.

### To Reproduce
```
from docstring_inheritance import GoogleDocstringInheritanceMeta


class Parent(metaclass=GoogleDocstringInheritanceMeta):
    """Parent class

    Attributes:
        w: Description for w
        x: Description for x
        y: Description for y
    
    Args:
        a: arg
    """
    def __init__(self, a):
        self.a = a


class Child(Parent):
    """Child class

    Attributes:
        z: Description for z
        y: Overridden description for y

    Args:
        a: overwritten arg
    """
    def __init__(self, a):
        self.a = a


print(Child.__doc__)
```

### Full traceback

<details><summary>Full traceback</summary>

```python
Child class

Attributes:
    w: Description for w
    x: Description for x
    y: Overridden description for y
    z: Description for z
```

</details>

### Expected behavior

Inheritance of class-level docstring args.
```
Child class

Attributes:
    w: Description for w
    x: Description for x
    y: Overridden description for y
    z: Description for z

Args:
    a: overwritten arg
```

### Environment information

```bash
python -m griffe_inherited_docstrings.debug  # | xclip -selection clipboard
```

- __System__: Linux-6.1.112+-x86_64-with-glibc2.39
- __Python__: cpython 3.10.15 (/home/user/miniforge3/envs/mgen/bin/python)
- __Environment variables__:
- __Installed packages__:
  - `griffe-inherited-docstrings` v1.1.1
### Additional context

Really love the package, thank you for building.

**Comment by pawamoy** [comment]
Hi @cnellington, thanks for the report.

> but currently only attributes are inherited

What do you mean? You're mentioning attributes, which are Griffe objects, yes, and can therefore be inherited. But "arguments" sections in docstrings are not objects (they are just sections in docstrings), so the concept of inheritance doesn't apply there. Whole docstrings can be inherited, yes, thanks to this extension.

> Args in class docstring also seem to work fine within vanilla mkdocstrings, but only break with inheritance.

What do you mean by "working fine", and "break with inheritance"? What breaks?

> full traceback

I'm not sure what you included there. Is that what you expect, or what you get?

> Inheritance of class-level docstring args.

Do you mean "inheritance of class-level docstrings? Like, if `Child` doesn't declare a docstring, it should inherit `Parent`'s docstring? And if `Child` declares a docstring if the `merge` option is enabled, it should be merged with `Parent`'s docstring? In short, what we do for methods, but for classes as well?

---

It sounds like you want docstrings *sections* to be merged? That's not possible (yet).

**Comment by cnellington** [comment]
Apologies for the very delayed reply. I believe this package was the wrong place for the issue. I've moved it over to https://github.com/AntoineD/docstring-inheritance/issues/19.

**Comment by pawamoy** [comment]
Ah, no worries! I indeed wondered for a second if you had reported in the wrong project 😄 Thank you for letting me know!
